### ISSUE TITLE
Failed to `dotnet new classlib` command in tutorial.

### ISSUE THREAD

**Issue by hskwakr** [dotnet/docs.ja-jp#1066]
[フィードバックをこちらに入力してください]
## Introduction  

Please let me know if this contents is not an appropriate as issue.  

Please let me know if there is any missing information in this message.  
Also, please let me know if you have any helpful information on this issue.  

## Issue  

I tried to this tutorial:  
https://docs.microsoft.com/ja-jp/dotnet/core/tutorials/creating-app-with-plugin-support

And I failed the `dotnet new classlib -o PluginBase` command:  

```powershell  
PS C:\...\AssemblyLoadContext> dotnet new classlib -o PluginBase  
The template "Class library" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on PluginBase\PluginBase.csproj...
C:\...\AssemblyLoadContext\PluginBase\PluginBase.csproj : error NU1100: '.NETStandard,Version=v2.0' に対する 'NETStandard.Library (>= 2.0.3)' を解決できま
せん。
  C:\...\AssemblyLoadContext\PluginBase\PluginBase.csproj の復元が
 179.49 ms で失敗しました。

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```

## MEMO  

I pushed my code to GitHub:  
https://github.com/hskwakr/AssemblyLoadContext/tree/step1.1  

My sell  
```powershell
PS C:\...\AssemblyLoadContext> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

My .NET Core
```powershell
PS C:\...\AssemblyLoadContext> dotnet --info
.NET Core SDK (global.json を反映):
 Version:   3.1.100
 Commit:    cd82f021f4

ランタイム環境:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]    
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## Thank you for reading.  

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 06023407-704f-0ace-e89a-eedd9f95a007
* Version Independent ID: f25a6e1a-cb10-867b-0522-a377bf9d016b
* Content: [プラグインがある .NET Core アプリケーションを作成する - .NET Core](https://docs.microsoft.com/ja-jp/dotnet/core/tutorials/creating-app-with-plugin-support)
* Content Source: [docs/core/tutorials/creating-app-with-plugin-support.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/core/tutorials/creating-app-with-plugin-support.md)
* Product: **dotnet-core**
* GitHub Login: @jkoritzinsky
* Microsoft Alias: **jekoritz**

**Comment by srvbpigh** [comment]
Hello, @hskwakr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #16323](https://github.com/dotnet/docs/issues/16323) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
こんにちは、@hskwakr  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/dotnet/docs/issues/16323) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
