### ISSUE TITLE
"種類" needs to be replaced with "型" 

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/docs.ja-jp#1147]
https://docs.microsoft.com/ja-jp/dotnet/visual-basic/reference/language-specification/types

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 64dd12fc-3c54-f9c4-1510-f4903180e919
* Version Independent ID: 7448c982-e270-1f29-9af7-370af0c5fa79
* Content: [種類Types](https://docs.microsoft.com/ja-jp/dotnet/visual-basic/reference/language-specification/types)
* Content Source: [spec/types.md](https://github.com/dotnet/vblang.ja-jp/blob/d2ff581bfed161bd2ab1cc9abb78919ec0899c58/spec/types.md)
* Product: **dotnet-visualbasic**
* Technology: **vb-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by hyoshioka0128** [comment]
ja-jp:
![types](https://user-images.githubusercontent.com/40815708/71578169-63c25880-2b3a-11ea-8f63-43a8e0d11e0f.png)

**Comment by srvbpigh** [comment]
こんにちは、@hyoshioka0128   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/visual-basic/reference/language-specification/types   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
