### ISSUE TITLE
1

### ISSUE THREAD

**Issue by kakisoft** [dotnet/docs.ja-jp#116]
ビハインドコードも併せて掲載頂けると幸いです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a1b56804-34b3-7133-437f-34f7ad919b72
* Version Independent ID: f0490a67-2a64-f2b0-a8c2-13dfe5a6a686
* Content: [Model-View-View Model を利用した汎用性のあるクラス ライブラリの使用](https://docs.microsoft.com/ja-jp/dotnet/standard/cross-platform/using-portable-class-library-with-model-view-view-model)
* Content Source: [docs/standard/cross-platform/using-portable-class-library-with-model-view-view-model.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/standard/cross-platform/using-portable-class-library-with-model-view-view-model.md)
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by gosali** [comment]
こんにちは、@Kakisoft 

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #6098](https://github.com/dotnet/docs/issues/6098) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@kakisoft



ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/dotnet/docs/issues/6098) を確認してください。 



記事の品質向上にご協力いただき誠にありがとうございました。  



敬具 

Microsoft DOCS International Team
