### ISSUE TITLE
 About title

### ISSUE THREAD

**Issue by kakisoft** [dotnet/docs.ja-jp#117]
掲載記事とは関係ありませんが、先ほどの投稿にて、タイトルを「コードビハインドについて」にしてフィードバックを送信しようとしたところ、
『指定されている形式で入力して下さい』という警告が出て、投稿が出来ませんでした。
（そのため、上記のようなタイトルでの投稿となりました。）

『指定されている形式』とはどのようなものか、詳細がわかる記事のURLを紹介頂けると幸いです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a1b56804-34b3-7133-437f-34f7ad919b72
* Version Independent ID: f0490a67-2a64-f2b0-a8c2-13dfe5a6a686
* Content: [Model-View-View Model を利用した汎用性のあるクラス ライブラリの使用](https://docs.microsoft.com/ja-jp/dotnet/standard/cross-platform/using-portable-class-library-with-model-view-view-model)
* Content Source: [docs/standard/cross-platform/using-portable-class-library-with-model-view-view-model.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/standard/cross-platform/using-portable-class-library-with-model-view-view-model.md)
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by gosali** [comment]
こんにちは、@kakisoft

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hi @nokura can you take a look at this issue?

Thanks

**Comment by nokura** [comment]
@kakisoft 様
ご不便をおかけして申し訳ありません。タイトルの形式について確認して返信いたします。
また、現在このページのローカライズを進めておりますので、参考にしていただければ幸いです。
https://docs.microsoft.com/ja-jp/teamblog/a-new-feedback-system-is-coming-to-docs
敬具
Microsoft DOCS International Team

**Comment by nokura** [comment]
@kakisoft  様
当方でも問題の状況を再現することができました。現在調査を進めておりますので、もうしばらくお待ちください。
![dotnet_githubissue117_repro](https://user-images.githubusercontent.com/13804190/43591417-2931584a-9628-11e8-90a7-3a27a6a1e5f7.png)

**Comment by nokura** [comment]
@kakisoft 様
当方でも問題の状況を再現することができました。現在調査を進めておりますので、もうしばらくお待ちください。
@LisandroSu, @gosali 
I was able to reproduce the issue. Here is the steps.
![dotnet_githubissue117_repro](https://user-images.githubusercontent.com/13804190/43591595-87a58ef0-9628-11e8-9a6c-2e39288d18c9.png)

敬具
Microsoft DOCS International Team

**Comment by kakisoft** [comment]
nokura様
調査ありがとうございます。
返信頂いた内容に、特に疑問点はございませんので、クローズさせて頂きます。

お時間を頂き、ありがとうございました。
