### ISSUE TITLE
Mixed line endings in .md file

### ISSUE THREAD

**Issue by Isa-rentacs** [dotnet/docs.ja-jp#121]
In .md files, line endings within their header (```title```, ```description```, ```author``` etc) are CRLF while within body they're only LF. 
This is bit troublesome for me as VSCode normalizes the line endings to either CRLF or LF, and it introduces unnecessary whitespace changes. 
I checked the files in [dotnet/docs](https://github.com/dotnet/docs) repository and it seems it only contains CRLF.

The screenshot below is the file content of https://github.com/dotnet/docs.ja-jp/blob/live/docs/core/get-started.md. There is CRLF at ```0x1E``` and ```0x1F``` while there's only LF at ```0x219```
![image](https://user-images.githubusercontent.com/1147443/42044791-d882e2f0-7b34-11e8-86a1-743a7ed16958.png)

**Comment by DavidPrio** [comment]
Hello, @Isa-rentacs ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @Isa-rentacs 

The issue should be solved now. Can you confirm it?

Thanks,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello @Isa-rentacs 

Thank you for your feedback. 
  
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
