### ISSUE TITLE
[LOC] "操作 new" needs to be replaced with "new 演算子" 

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/docs.ja-jp#1215]
https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/language-specification/introduction

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 362f3e73-a902-45e6-382d-328a4552a235
* Version Independent ID: d4253465-4bfc-e473-f745-0d5e1ff4e76c
* Content: [概要Introduction - C# language specification](https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/language-specification/introduction)
* Content Source: [spec/introduction.md](https://github.com/dotnet/csharplang.ja-jp/blob/61761fcfe797043db13d94a7dce2b7af22dc8d9b/spec/introduction.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

I cannot repro the error,  there are no "操作 new" occurrences in this page

Kind regards,
Microsoft DOCS International Team

**Comment by hyoshioka0128** [comment]
Hi, @CeciAc  (I'm poor English.)
"operator" is mistranslated. (操作 → 演算子)

ja-jp:
![introduction_j](https://user-images.githubusercontent.com/40815708/71430765-0f217680-2711-11ea-908b-cd4d53045c76.png)

en-us:
![introduction_e](https://user-images.githubusercontent.com/40815708/71430747-fdd86a00-2710-11ea-955b-48c6b53e456e.png)

Thanks.

**Comment by hyoshioka0128** [comment]
Hi, @CeciAc 
I misunderstand.
ja-jp:
![introduction_j](https://user-images.githubusercontent.com/40815708/71431486-74776680-2715-11ea-928a-568e38955108.png)

I misread a "new operation" as a "new operator"  in en-us..
Closed #1215.
 Thanks.
