### ISSUE TITLE
mistranslation(ja), in enum reference.

### ISSUE THREAD

**Issue by zfhrp6** [dotnet/docs.ja-jp#135]
"In this enumeration, the sequence of elements is forced to start from 1 instead of 0." is translated to "この列挙型では、要素の並びは 1 からではなく、 0から開始します。".

この時，列挙型は `1` から開始するため誤訳です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: be8ee5fd-7f5b-cf11-2ced-175a82c006f5
* Version Independent ID: f8cc2bf8-c049-7fce-3b55-73cda3cf3de2
* Content: [enum キーワード (C# リファレンス)](https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/keywords/enum)
* Content Source: [docs/csharp/language-reference/keywords/enum.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/language-reference/keywords/enum.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
こんにちは、@zfhrp6
フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by zfhrp6** [comment]
sorry. I overlooked these #54 #57 #60.
I think this issue is the same.

**Comment by LisandroSu** [comment]
Hello, @zfhrp6 

Thank you for the update

Was the issue fixed in those PRs?

Regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @zfhrp6 

Sorry for the delay. The issue was sent to our team to check on the changes and we will update you soon on the results.

Thank you,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @zfhrp6, 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/keywords/enum. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
