### ISSUE TITLE
Improvement the feedback form

### ISSUE THREAD

**Issue by runceel** [dotnet/docs.ja-jp#137]
Hi team,

Could you add that the feedback will be wrote to GitHub issues from the feedback form?

In English, that is already wrote.(see below)
![image](https://user-images.githubusercontent.com/79868/43233492-237c8a72-90b1-11e8-914e-7f90a2be2254.png)

In Japanese, there is not that.
![image](https://user-images.githubusercontent.com/79868/43233553-6b87924e-90b1-11e8-9de5-bc95d2691b83.png)

I think that it is very important to clear the feedback process.

**Comment by ryokaji** [comment]
@runceel May I know the location (if you found) ?

**Comment by runceel** [comment]
@ryokaji 
I found a following issue.
https://github.com/MicrosoftDocs/Contribute/issues/46

This is same as my issue. I'm waiting progress for the above issue.

**Comment by mairaw** [comment]
I'd suggest you file an issue at https://github.com/MicrosoftDocs/feedback. That's where the engineering team is constantly triaging this kind of feedback. The Contribute repo is about the contributor guide at https://docs.microsoft.com/en-us/contribute/. And given that the feedback is in Japanese, it might take longer for the team to review. Thanks!

**Comment by Makopo** [comment]
I believe I have covered that in https://github.com/MicrosoftDocs/feedback/issues/554 .
@Powerhelmsman @bodhigautam @SonjaSaltzman is addressing to this issue.
