### ISSUE TITLE
「DO/DO NOT」等とその後に続く日本語の間に空白が欲しい

### ISSUE THREAD

**Issue by masaru-b-cl** [dotnet/docs.ja-jp#140]
英語ページと同様に、

✓ **DO**フィールドの名前で pascal 表記を使用を使用します。

ではなく

✓ **DO** フィールドの名前で pascal 表記を使用を使用します。

のように「DO/DO NOT」などの後に1文字空白があるだけで、可読性が大きく変わるため、本ページに限らずスタイルガイドライン全体も含めて修正を検討してほしい。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1cd21cac-a7e8-13ca-d940-3447312871ca
* Version Independent ID: 7f3307e9-5563-e28f-cdad-9b6e33358c6b
* Content: [型のメンバーの名前](https://docs.microsoft.com/ja-jp/dotnet/standard/design-guidelines/names-of-type-members#feedback)
* Content Source: [docs/standard/design-guidelines/names-of-type-members.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/standard/design-guidelines/names-of-type-members.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LisandroSu** [comment]
こんにちは、@masaru-b-cl

ご協力に深く感謝いたします。Microsoft   の担当チームがお寄せいただいたフィードバックを確認しましたところ、既にログ記録されている内容であることがわかりました。
 
問題 # https://github.com/dotnet/docs.ja-jp/pull/138   をご確認ください。そのため、この問題は重複により終了とさせていただきます。
 
敬具
Microsoft DOCS International   Team

**Comment by nokura** [comment]
@masaru-b-cl 様
ご指摘の点、改善いたします。

**Comment by nokura** [comment]
@masaru-b-cl 様
ご指摘の点、改善いたします。
敬具
Microsoft DOCS International Team

**Comment by nokura** [comment]
@LisandroSu 
Actually, this feedback is not the same as #118. The space between 'DO/DO NOT/CONSIDER' and the following word is missing, which is valid input and we have to fix it.
Thanks,
Nokura

**Comment by LisandroSu** [comment]
こんにちは、@masaru-b-cl

フィードバックをお送りいただきありがとうございました。
 
Microsoft   の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント   サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/standard/design-guidelines/names-of-type-members#feedback
 
記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。

敬具
Microsoft DOCS International   Team

**Comment by masaru-b-cl** [comment]
@LisandroSu @nokura 

フィードバックに対して、改善していただけるとのこと、うれしく思います。
ご対応ありがとうございました。

本コメント時点でまだdocsの該当ページの更新はされていないようですが、また後日確認してみます。

**Comment by masaru-b-cl** [comment]
https://docs.microsoft.com/ja-jp/dotnet/standard/design-guidelines/names-of-type-members

を確認したところ、更新されていました。

しかし #138 の @nokura 様の回答
https://github.com/dotnet/docs.ja-jp/pull/138#issuecomment-408285685
では

> このたびは推奨、非推奨、ではなく、DO・DO NOT のとおり英語表記を残す決定をいたしました。

とありますが、次の画像のように、"実行: "になってしまっていました。

!["DO"が"実行"になっている](https://user-images.githubusercontent.com/781507/43447114-b33baf52-94e5-11e8-9ab5-3cbad84ad465.png)

このドキュメントにおいては"DO"の意味は"実行"ではないはずです。
"DO"は訳さずに"DO"のままにしていただきたいです。

なお、"実行:"の":"(コロン)については、個人的には空白だけよりは好ましいと感じます。

したがって、最終的には次のようになっていることが理想です。

> **DO:** フィールドの名前で pascal 表記を使用を使用します。

**Comment by masaru-b-cl** [comment]
直っていることを確認しました。対応ありがとうございました。
