### ISSUE TITLE
"example" keyword is not need translate.

### ISSUE THREAD

**Issue by nogic1008** [dotnet/docs.ja-jp#144]
This English title is "&lt;example&gt;".
example is keyword, so it's not need translate "&lt;例&gt;".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e6f92e76-2785-188b-6046-ec741144fcd0
* Version Independent ID: 8708e9f1-a45f-4106-6ba2-bf2e56f76aab
* Content: [&lt;例&gt; (C# プログラミング ガイド)](https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/xmldoc/example)
* Content Source: [docs/csharp/programming-guide/xmldoc/example.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/programming-guide/xmldoc/example.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hello, @nogic1008 , 
  
Thank you for your feedback. 
  
Another user created a [pull request](https://github.com/dotnet/docs.ja-jp/pull/147) for this issue. We will continue to work with the pull request as it also fixes another word that shouldn't be translated.
 
Kind regards, 
Microsoft DOCS International Team
