### ISSUE TITLE
Japanese docs is broken

### ISSUE THREAD

**Issue by diontools** [dotnet/docs.ja-jp#155]
140b095a.localized-strings.js is 404.
![msdocs](https://user-images.githubusercontent.com/12995573/45469387-45c5be80-b764-11e8-9280-67f6fc33c158.PNG)

**Comment by mairaw** [comment]
/cc @nokura @SonjaSaltzman @ericvt 

Other languages seem to be broken as well.

**Comment by mairaw** [comment]
I think we can close this issue. I managed to repro this issue but it went away after a few hours.

**Comment by diontools** [comment]
The site is correctly displayed now. Thank you for your corresponding.
