### ISSUE TITLE
ConcurrentQueue(T) 対 Queue(T)の日本語翻訳の誤り

### ISSUE THREAD

**Issue by TyounanMOTI** [dotnet/docs.ja-jp#158]
英語：
In pure producer-consumer scenarios, where the processing time for each element is very small (a few instructions), then System.Collections.Concurrent.ConcurrentQueue&lt;T&gt; can offer modest performance benefits over a System.Collections.Generic.Queue&lt;T&gt; that has an external lock.

誤った現状の翻訳：
純粋プロデューサー/コンシューマー シナリオで、各要素の処理時間がとても短い (命令が少ない) 場合には、外部ロックを使用する System.Collections.Concurrent.ConcurrentQueue&lt;T&gt; よりも System.Collections.Generic.Queue&lt;T&gt; の方が若干優れたパフォーマンスを得られます。

正しい翻訳：
純粋プロデューサー/コンシューマー シナリオで、各要素の処理時間がとても短い (命令が少ない) 場合には、外部ロックを使用する System.Collections.Generic.Queue&lt;T&gt; よりも System.Collections.Concurrent.ConcurrentQueue&lt;T&gt; の方が若干優れたパフォーマンスを得られます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: dfef78b3-a48d-be0c-3ccd-a789e0e4eaef
* Version Independent ID: 0186f87a-b98e-8a05-d09f-be3de55928e2
* Content: [スレッド セーフなコレクションを使用する状況](https://docs.microsoft.com/ja-jp/dotnet/standard/collections/thread-safe/when-to-use-a-thread-safe-collection#feedback)
* Content Source: [docs/standard/collections/thread-safe/when-to-use-a-thread-safe-collection.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/standard/collections/thread-safe/when-to-use-a-thread-safe-collection.md)
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by CeciAc** [comment]
こんにちは、@TyounanMOTI

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@TyounanMOTI

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/standard/collections/thread-safe/when-to-use-a-thread-safe-collection#feedback   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  


敬具  
Microsoft DOCS International Team
