### ISSUE TITLE
On Visual Studio 2019 .NET console app project, [View Application Events] button is not Available

### ISSUE THREAD

**Issue by egplantman** [dotnet/docs.ja-jp#1662]
「未処理の例外をログに記録するには」の項において:

Visual Studio 2019で作成した.NET Framework コンソール アプリ プロジェクトでは「アプリケーション イベントの表示」ボタンが使用できない状態でした。

また、プロジェクト フォルダーの中にはApplicationEvents.vb ファイルが見つかりませんでした。このファイルの場所もお教えいただければと思います。

"To log an unhandled exception" section:
On my .NET Framework console application project, [View Application Events] button is not available.

Also, in my project folder, "ApplicationEvents.vb" is missing.
Could you tell us the file path?

I am sorry that I am not good at English, and not good at Github...

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 33c50630-612b-c8d8-7438-fd7219d66fc5
* Version Independent ID: 2a3eb119-d2c9-dbd9-23c1-30654751f24d
* Content: [方法: 例外をログに記録する - Visual Basic](https://docs.microsoft.com/ja-jp/dotnet/visual-basic/developing-apps/programming/log-info/how-to-log-exceptions#to-log-an-unhandled-exception)
* Content Source: [docs/visual-basic/developing-apps/programming/log-info/how-to-log-exceptions.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/developing-apps/programming/log-info/how-to-log-exceptions.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by srvbpigh** [comment]
Hello, @egplantman
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [dotnet/docs #16804](https://github.com/dotnet/docs/issues/16804) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
こんにちは、@egplantman  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/dotnet/docs/issues/16804) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
