### ISSUE TITLE
メソッド名が日本語に訳されています。

### ISSUE THREAD

**Issue by gushwell** [dotnet/docs.ja-jp#1663]
ここは訳さず、メソッド名のままが正しいです。
除く　-&gt;　Except
交差	　-&gt;　Intersect
和集合　-&gt;　Union

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fbdace9d-6fa0-0aec-25b4-df6f414001d7
* Version Independent ID: 77eff122-b9a5-2b1f-3a68-df302cb46194
* Content: [セット操作 (C#)](https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/concepts/linq/set-operations?source=docs)
* Content Source: [docs/csharp/programming-guide/concepts/linq/set-operations.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/programming-guide/concepts/linq/set-operations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @gushwell
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@gushwell   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/concepts/linq/set-operations?source=docs   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
