### ISSUE TITLE
メソッドの表のメソッド名が日本語に訳されています。

### ISSUE THREAD

**Issue by gushwell** [dotnet/docs.ja-jp#1664]
以下が正しいです。

すべて　-&gt;  All
どれでも可 -&gt; Any
内容 -&gt; Contains

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: da65be87-16ea-ebcb-e098-6dbf3579152f
* Version Independent ID: 045d5185-5b9c-effc-c542-75192e320d29
* Content: [量指定子操作 (C#)](https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/concepts/linq/quantifier-operations)
* Content Source: [docs/csharp/programming-guide/concepts/linq/quantifier-operations.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/programming-guide/concepts/linq/quantifier-operations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @gushwell
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@gushwell   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/concepts/linq/quantifier-operations   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
