### ISSUE TITLE
メソッド名Last が日本語に訳されてます

### ISSUE THREAD

**Issue by gushwell** [dotnet/docs.ja-jp#1665]
'末尾'と訳されていますが、正しくは'Last'です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 425902b5-2b2a-c899-91fb-44aa9ea3dc1b
* Version Independent ID: e2866096-c7fe-61cb-b53b-6fa0f78800f5
* Content: [要素操作 (C#)](https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/concepts/linq/element-operations)
* Content Source: [docs/csharp/programming-guide/concepts/linq/element-operations.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/programming-guide/concepts/linq/element-operations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @gushwell
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@gushwell   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/concepts/linq/element-operations   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
