### ISSUE TITLE
[typo] 誤字があります。

### ISSUE THREAD

**Issue by YusukeOno** [dotnet/docs.ja-jp#1669]
> 下位互換とは、プラットフォームの特定のバージョンで開発されたアプリが、そのプラットフォームの新しいバージョンでも実行できることを意味します。 .NET Framework では、下位互換性が最大限に高め67られています。 

→　下位互換性が最大限に高め67られています。 

「67」は不要です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 20441ff4-e507-5773-3518-32d138a7d62a
* Version Independent ID: a4873f79-ac89-e984-d713-7815dd5bab58
* Content: [.NET Framework のバージョンの互換性](https://docs.microsoft.com/ja-jp/dotnet/framework/migration-guide/version-compatibility#feedback)
* Content Source: [docs/framework/migration-guide/version-compatibility.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/framework/migration-guide/version-compatibility.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by srvbpigh** [comment]
Hello, @YusukeOno
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
