### ISSUE TITLE
C#のコード例が表示されていないようです。

### ISSUE THREAD

**Issue by yucchiy** [dotnet/docs.ja-jp#1673]
C#のコード例が表示されていないようです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1e8e455c-1162-d046-ed70-22dfe96cbbad
* Version Independent ID: 9448a018-a06c-0ae5-049b-c4c424d1df9a
* Content: [インターフェイスのプロパティ - C# プログラミング ガイド](https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/classes-and-structs/interface-properties#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/interface-properties.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/programming-guide/classes-and-structs/interface-properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @yucchiy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
フィードバックをお送りいただきありがとうございました。  

Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/classes-and-structs/interface-properties#feedback   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
