### ISSUE TITLE
日本語訳が異なるようです。

### ISSUE THREAD

**Issue by tfukumori** [dotnet/docs.ja-jp#1674]
日本語ドキュメントの以下の部分について、日本語訳が逆の意味になっているのではないかと思います。

 # English

> Event Handling
> Use Handles rather than AddHandler:

https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/program-structure/coding-conventions#event-handling

# 日本語訳（現在）

> イベント処理
> Handles ではなく AddHandler を使用します。

https://docs.microsoft.com/ja-jp/dotnet/visual-basic/programming-guide/program-structure/coding-conventions#event-handling

# 日本語訳（おそらくこちらが妥当である）：

> イベント処理
> AddHandler ではなく Handles を使用します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 13b0704e-6aae-5c96-7aca-bcb1dd222d82
* Version Independent ID: 76d496a8-a09e-c844-536f-63a34229876c
* Content: [コーディング規則 - Visual Basic](https://docs.microsoft.com/ja-jp/dotnet/visual-basic/programming-guide/program-structure/coding-conventions)
* Content Source: [docs/visual-basic/programming-guide/program-structure/coding-conventions.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/program-structure/coding-conventions.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by srvbpigh** [comment]
Hello, @tfukumori
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@tfukumori 様:

投稿いただき、ありがとうございます。

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。

サポートいただきありがとうございます。

Microsoft DOCS グローバル エクスペリエンス チーム
