### ISSUE TITLE
タイポ

### ISSUE THREAD

**Issue by atsusheep** [dotnet/docs.ja-jp#1676]
macOS では、このツールでアンインストールできのは /usr/local/share/dotnet フォルダーにある SDK とランタイムのみです。
→
macOS では、このツールでアンインストールできるのは /usr/local/share/dotnet フォルダーにある SDK とランタイムのみです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 289d3b2b-8b21-d0a0-10fa-9a8b3fdb62ce
* Version Independent ID: 3145ef37-2a19-e3ca-ba78-95c2f1a41a6b
* Content: [アンインストール ツール - .NET Core](https://docs.microsoft.com/ja-jp/dotnet/core/additional-tools/uninstall-tool?tabs=windows#feedback)
* Content Source: [docs/core/additional-tools/uninstall-tool.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/core/additional-tools/uninstall-tool.md)
* Product: **dotnet-core**
* GitHub Login: @sfoslund
* Microsoft Alias: **mairaw**

**Comment by srvbpigh** [comment]
Hello, @atsusheep
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
