### ISSUE TITLE
比較演算子が誤って翻訳されている

### ISSUE THREAD

**Issue by KisaragiEffective** [dotnet/docs.ja-jp#1688]
`&gt;?`が`&gt; ますか?`など、翻訳されるべきでないところまで翻訳されている

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3d56ffdb-b420-1ddc-1513-ae77a2865111
* Version Independent ID: 42a1a41c-6f9c-7885-7128-01401fd93a63
* Content: [Null 許容の演算子 - F#](https://docs.microsoft.com/ja-jp/dotnet/fsharp/language-reference/symbol-and-operator-reference/nullable-operators)
* Content Source: [docs/fsharp/language-reference/symbol-and-operator-reference/nullable-operators.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/fsharp/language-reference/symbol-and-operator-reference/nullable-operators.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by srvbpigh** [comment]
Hello, @KisaragiEffective
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@KisaragiEffective  様: 

投稿いただき、ありがとうございます。 

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。 

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。 

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。 

サポートいただきありがとうございます。 

Microsoft DOCS グローバル エクスペリエンス チーム
