### ISSUE TITLE
【クラスの概要】のコードの記述箇所

### ISSUE THREAD

**Issue by Misaki0306** [dotnet/docs.ja-jp#1699]
【クラスの概要】のコードの記述箇所が分かりませんでした。

コードの記述先がProgram.csなのかTransaction.csか明確ではありません。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [クラスおよびオブジェクト - C# チュートリアルの概要](https://docs.microsoft.com/ja-jp/dotnet/csharp/tutorials/intro-to-csharp/introduction-to-classes#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/tutorials/intro-to-csharp/introduction-to-classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Misaki0306
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #18291](https://github.com/dotnet/docs/issues/18291) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
こんにちは、@Misaki0306  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/dotnet/docs/issues/18291) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
