### ISSUE TITLE
The sentence is harder to understand than before.

### ISSUE THREAD

**Issue by nozsasaki0202** [dotnet/docs.ja-jp#170]
in japanese.
The sentence is harder to understand than before.
There is a thing that I do not understand the meaning of the table of contents.
I can not reach the target content.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d69553b4-b9c9-ebfa-b7be-3bce2d94f3d5
* Version Independent ID: e9fc7e1d-253a-e5b6-b5bc-f54d14678900
* Content: [方法 : スライダーの目盛りをカスタマイズする](https://docs.microsoft.com/ja-jp/dotnet/framework/wpf/controls/how-to-customize-the-ticks-on-a-slider#feedback)
* Content Source: [docs/framework/wpf/controls/how-to-customize-the-ticks-on-a-slider.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/framework/wpf/controls/how-to-customize-the-ticks-on-a-slider.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @nozsasaki0202,
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @nozsasaki0202 
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @nozsasaki0202 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
