### ISSUE TITLE
アンカータグ<a> が空タグを表現しようとしているが、空タグは許容されていない為、アンカータグ始まりと認識されてしまい表示が崩れています

### ISSUE THREAD

**Issue by juner** [dotnet/docs.ja-jp#1722]
`<a name="rule-2"/>` という空のアンカータグが挿入されていますが、 `<a>` タグは `<a/>` の表現が許されていないタグな為、`<a>` と認識されており、`</a>` が発生するまでその範囲がリンクの様な表記になっています。

![image](https://user-images.githubusercontent.com/753914/85819195-e9ebee80-b7ad-11ea-98b0-4b496d0ed6e9.png)

ちなみに[英語版の記事](https://docs.microsoft.com/en-us/dotnet/standard/memory-and-spans/memory-t-usage-guidelines)では `<p><a name="rule-2"></a></p>` の表現になっています。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4819512e-1044-1c57-0de1-447164220fd5
* Version Independent ID: d6cf8d26-fb2f-7138-f0c7-ab529a5b9cde
* Content: [Memory&lt;T&gt; と Span&lt;T&gt; の使用ガイドライン](https://docs.microsoft.com/ja-jp/dotnet/standard/memory-and-spans/memory-t-usage-guidelines)
* Content Source: [docs/standard/memory-and-spans/memory-t-usage-guidelines.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/standard/memory-and-spans/memory-t-usage-guidelines.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
@juner 様: 

Microsoft では、内部プロセスおよびエンジニアリング パイプラインを強化しています。このため、フィードバックの処理に遅延が生じています。

記事への投稿に感謝しております。今後ともご理解とご協力をお願い申し上げます。

**Comment by juner** [comment]
いつの間にか改善した様なので閉じます。ありがとうございます。
