### ISSUE TITLE
Broken  docs page

### ISSUE THREAD

**Issue by gekka** [dotnet/docs.ja-jp#173]
This docs.microsoft.com page is breaking and not being updated.

![drag-and-drop-overview](https://user-images.githubusercontent.com/10055381/48329713-393ee300-e68d-11e8-99f6-61f82e2894a4.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 08e8a3ee-62b2-0e3b-4590-f42812a84e1b
* Version Independent ID: cdce1367-8c37-02b8-a7ba-cb11eca447af
* Content: [ドラッグ アンド ドロップの概要](https://docs.microsoft.com/ja-jp/dotnet/framework/wpf/advanced/drag-and-drop-overview)
* Content Source: [docs/framework/wpf/advanced/drag-and-drop-overview.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/framework/wpf/advanced/drag-and-drop-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi @gekka 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/dotnet/framework/wpf/advanced/drag-and-drop-overview. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
