### ISSUE TITLE
 Windows フォームのサイズを変更するで、System.AtgumentOutOfRangeExceptionが発生する

### ISSUE THREAD

**Issue by bigston666** [dotnet/docs.ja-jp#175]
アプリケーションは停止することはないが、VisualStudioでのデバック出力に、System.AtgumentOutOfRangeExceptionの例外エラーログが残る。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7034cc03-e233-714b-5fc6-9562ced11d98
* Version Independent ID: c44e3792-805e-d883-7d31-fe5e54110255
* Content: [方法 : Windows フォームのサイズを変更する](https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/how-to-resize-windows-forms)
* Content Source: [docs/framework/winforms/how-to-resize-windows-forms.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/framework/winforms/how-to-resize-windows-forms.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
こんにちは、@bigston666
 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 
 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 
 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
 敬具 
Microsoft DOCS International Team
