### ISSUE TITLE
The typo at the abstract（冒頭に誤字があります）

### ISSUE THREAD

**Issue by Kuniwak** [dotnet/docs.ja-jp#176]
&gt; このセクションでは、C# のキーワード、演算子、特殊文字、プリプロセッサ ディレクティブ、コンパイラ オプション、およびコンパイラのエラーと警告ン関する参考資料を紹介します。

&lt;dl&gt;
&lt;dt&gt;Wrong
&lt;dd&gt;警告ン関する
&lt;dt&gt;Correct
&lt;dd&gt;警告に関する
&lt;/dl&gt;

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a60b6e17-36cf-bd6c-1b76-d38f1760a816
* Version Independent ID: 0fdeaa81-c3c2-c290-224e-792fcee9b297
* Content: [C# リファレンス](https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/index#feedback)
* Content Source: [docs/csharp/language-reference/index.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/language-reference/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
こんにちは、@Kuniwak

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/index#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
