### ISSUE TITLE
translation issue 名前付けのガイドライン

### ISSUE THREAD

**Issue by critical-bug** [dotnet/docs.ja-jp#179]
Japanese translation doesn't make sense.

en: Following a consistent set of naming conventions in the development of a framework can be a major contribution to the framework’s usability.
ja (bad): 次の一貫した開発フレームワークの名前付け規則のセットと、フレームワークの使いやすさへの主要な貢献を指定できます。
ja (suggestion): フレームワーク開発で一貫した名前付け規則に従うことは、フレームワークの使いやすさへの主要な貢献となりえます。

en: Beyond consistency of form, names of framework elements must be easily understood and must convey the function of each element.
ja (bad): フォームの整合性を超えるフレームワーク要素の名前は簡単に理解する必要があり、各要素の機能を伝達する必要があります。
ja (suggestion): 形の一貫性の上では、フレームワーク要素の名前は簡単に理解され、各要素の機能を伝えるでしょう。

en: Although adopting these naming conventions as general code development guidelines would result in more consistent naming throughout your code, you are required only to apply them to APIs that are publicly exposed (public or protected types and members, and explicitly implemented interfaces).
ja (bad): パブリックに公開される Api に適用するには、のみ必要がありますが、一般的なコードの開発のガイドラインが、コード全体でより一貫性のある名前付けになると、これらの名前付け規則を採用すること、(パブリックまたはプロテクト型とメンバー、および明示的に実装されたインターフェイス)。
ja (suggestion): これらの名前付け規約を一般的なコード開発ガイドラインとして採用することはあなたのコード全体により一貫した名前付けをもたらしはしますが、パブリックに公開されたAPI（public または protected な型やメンバー、および明示的に実装されたインターフェイス）にだけ適用すればよいです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a0519029-efb1-d275-7214-873bed952c2d
* Version Independent ID: a3b0d4ad-fc4b-032c-25c7-d7f914884022
* Content: [名前付けのガイドライン](https://docs.microsoft.com/ja-jp/dotnet/standard/design-guidelines/naming-guidelines)
* Content Source: [docs/standard/design-guidelines/naming-guidelines.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/standard/design-guidelines/naming-guidelines.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
こんにちは、@critical-bug

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@critical-bug

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/standard/design-guidelines/naming-guidelines

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
