### ISSUE TITLE
A merged linguistic suggestion PR has been rolled back.

### ISSUE THREAD

**Issue by kanonji** [dotnet/docs.ja-jp#215]
#152 has been rolled back by https://github.com/dotnet/docs.ja-jp/commit/f7c9787b99366377ff040d1717d24f12b79ed65e#diff-f13256e81c2e014f2a7dfaf4040ffd73
Is that intended?

**Comment by CeciAc** [comment]
Hello @kanonji 
The file was updated after the PR implementation and it may be reverted due to subtle differences with the original source.
You can create a new PR for this.

Kind regards,
Microsoft DOCS International Team

**Comment by kanonji** [comment]
@CeciAc My PR #152 has fixing a broken sentence. So current document has a broken sentence too.
I don't think this is subtle differences but I don't want to re-create same PR again.
