### ISSUE TITLE
Which branch to send PRs to?

### ISSUE THREAD

**Issue by terasato** [dotnet/docs.ja-jp#275]
I usually send my PRs to `live` branch.
This is because when I click `Edit` on an article in docs.microsoft.com, the website guides me to send a PR to the branch.

But recently I found that `CONTRIBUTING.md` in this repository describes we should send PRs to `dotnet/docs/master`.

Which branch to send PRs to?

**Comment by CeciAc** [comment]
Hello, @terasato 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @JasonCard 
can you please check this?

**Comment by JasonCard** [comment]
Hello, @terasato
 
Thank you for your question.
For contribution toward localized languages such as Japanese, you can continue to open PR in `live` branch where the `Edit` button takes you. 
`CONTRIBUTING.md` was written for contribution toward the English version, where contributions are setup to open PR in `master` branch first, which is later merged to `live` branch when ready to publish.  GitHub repos for localized languages do not use `master` branch and only use `live` branch, so contribution is setup to open PR in `live` branch.  
I've opened this [GitHub Issue](https://github.com/dotnet/docs/issues/9770) to address this issue in `CONTRIBUTING.md`.  
Please let us know if you have any further questions.  

Kind regards,
Microsoft DOCS International Team
cc @CeciAc
