### ISSUE TITLE
Typo 誤字があります。

### ISSUE THREAD

**Issue by shocci1214** [dotnet/docs.ja-jp#373]
>>ディレクティブとして使用: 名前空間のエイリアスを作成すとき、または他の名前空間で定義されてい>>る型をインポートするとき。 「using ディレクティブ」を参照してください。

→作成するとき

「る」が抜けています。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a731ad7b-0655-4bb3-2478-0cbb4d063f02
* Version Independent ID: 2ba9241c-0836-d05e-5ba1-ebc5498d2009
* Content: [using - C# リファレンス](https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/keywords/using)
* Content Source: [docs/csharp/language-reference/keywords/using.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/language-reference/keywords/using.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
こんにちは、@shocci1214

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@shocci1214

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/keywords/using

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
