### ISSUE TITLE
sizeof(long) は 8 じゃないですか？

### ISSUE THREAD

**Issue by juner** [dotnet/docs.ja-jp#47]
表ではsizeof(long)の値が9になっているのですが。
実際の値は8ではないでしょうか？
https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/language-reference/keywords/sizeof.md
https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/keywords/sizeof

**Comment by mairaw** [comment]
/cc @nokura 

This seems like a problem with the localized version. English version correctly displays 8:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/sizeof

**Comment by nokura** [comment]
Thank you for pointing it out. The fix will be published live in few days.

**Comment by mairaw** [comment]
I just noticed that it had one more wrong. I'll do a new PR.

**Comment by nokura** [comment]
Thank you for catching it up. We are fixing this topic. I will close this issue when I verify the fix in Live.

**Comment by nokura** [comment]
The issue is fixed. Thank you for your support @juner
