### ISSUE TITLE
Revert  5b6751358b9fa8bdf28af1201ecb11cf9e5c88ed

### ISSUE THREAD

**Issue by tanaka-takayoshi** [dotnet/docs.ja-jp#5]
Hi, I submitted PR #3 to fix C# and F# in the top page. However I found the someone overrides this fix with commit 5b6751358b9fa8bdf28af1201ecb11cf9e5c88ed.
Could you revert this commit?
Besides, is it be possible to stop @OpenLocalizationService? It appears OpenLocalizationService automatically commits the machine-translated contents but it contains translation errors. This page is important as it's the top page of the document. It's worth translate by hand to maintain natural  Japanese.

**Comment by mairaw** [comment]
Hi @tanaka-takayoshi,

You're right, your fix shouldn't have been overridden. The team should be checking on that.
The @OpenLocalizationService is the account for our localization automation process which should not override accepted changes.

/cc @nokura @SonjaSaltzman
