### ISSUE TITLE
マネージ vs マネージド

### ISSUE THREAD

**Issue by KageShiron** [dotnet/docs.ja-jp#570]
一部の形容詞(-ed系)の訳語が不統一です。
Translated words of adjectives (e.g. managed) are inconsistent.

Sample:
Managed Thread→マネージ スレッド or マネージド スレッド
Unmanaged Code→アンマネージ コード or アンマネージド コード

The document have both アンマネージ コード and アンマネージド コード in the same paragraph.
https://github.com/dotnet/docs.ja-jp/blob/2bbb630ec8a872b2b78f3169153c07d38f7d7b9f/docs/framework/security/secure-coding-guidelines-for-unmanaged-code.md

**Comment by CeciAc** [comment]
Hello, @KageShiron 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KageShiron 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://github.com/dotnet/docs.ja-jp/blob/2bbb630ec8a872b2b78f3169153c07d38f7d7b9f/docs/framework/security/secure-coding-guidelines-for-unmanaged-code.md

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
