### ISSUE TITLE
Doubled comma in first paragraph

### ISSUE THREAD

**Issue by tak-onda** [dotnet/docs.ja-jp#577]
"これは、ref または out キーワードと似ています。「ただし、、」"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6b1434b0-5459-7569-47f7-46bf33fc3953
* Version Independent ID: 8a4ae81b-1ae5-cbe6-d58b-df455414e245
* Content: [in パラメーター修飾子 - C# リファレンス](https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/keywords/in-parameter-modifier#feedback)
* Content Source: [docs/csharp/language-reference/keywords/in-parameter-modifier.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/language-reference/keywords/in-parameter-modifier.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @tak-onda 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @tak-onda 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/keywords/in-parameter-modifier

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
