### ISSUE TITLE
Raw Markdown text

### ISSUE THREAD

**Issue by grohiro** [dotnet/docs.ja-jp#582]
This document is broken. It looks like raw Markdown text is displayed without converting to HTML.
![スクリーンショット 2019-03-14 11 42 05](https://user-images.githubusercontent.com/6082303/54328021-b3896f00-464f-11e9-8ced-f809300e7f58.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 48c50f8f-5fee-2662-e48c-9ea185696a71
* Version Independent ID: c75f8faa-fabb-7ed7-c393-6745e11af397
* Content: [方法: コントロールをフォームの端を揃える](https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/controls/how-to-align-a-control-to-the-edges-of-forms)
* Content Source: [docs/framework/winforms/controls/how-to-align-a-control-to-the-edges-of-forms.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/framework/winforms/controls/how-to-align-a-control-to-the-edges-of-forms.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @grohiro 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @grohiro 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/controls/how-to-align-a-control-to-the-edges-of-forms

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
