### ISSUE TITLE
TOC for .NET Guide ja-jp document is not translated. 

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/docs.ja-jp#595]
https://docs.microsoft.com/ja-jp/dotnet/standard/

related issue: #594

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @hyoshioka0128 

Thank you for reporting this issue.
Table of contents are now displaying localized version in live page, so closing this issue.

Kind regards,
Microsoft DOCS International Team
cc @CeciAc
