### ISSUE TITLE
Regular Expression Language - Quick Reference

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs.ja-jp#605]
The **Matches** columns of the article */docs/standard/base-types/regular-expression-language-quick-reference.md* are still broken in [ja-jp](https://docs.microsoft.com/ja-jp/dotnet/standard/base-types/regular-expression-language-quick-reference), [ko-kr](https://docs.microsoft.com/ko-kr/dotnet/standard/base-types/regular-expression-language-quick-reference), [zh-cn](https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/regular-expression-language-quick-reference) and [zh-tw](https://docs.microsoft.com/zh-tw/dotnet/standard/base-types/regular-expression-language-quick-reference) repos.

As for the [Turkish](https://docs.microsoft.com/tr-tr/dotnet/standard/base-types/regular-expression-language-quick-reference) article, I assume that there is a difference between the prepositions. dotnet/docs#9993

@JasonCard

**Comment by JasonCard** [comment]
Hi @NextTurn 
Thank you for catching this issue again. 
I've started internal thread to follow up on this.

**Comment by JasonCard** [comment]
Hi @NextTurn,
We had our translators review and fix this article in mentioned languages. 
Thank you again for your feedback and please let us know if you still find any issues.
Kind regards,
Microsoft DOCS International Team
cc @CeciAc
