### ISSUE TITLE
Showing "## 関連項目 [イメージ、ビットマップ、アイコン、およびメタファイルの操作](working-with-images-bitmaps-icons-and-metafiles.md) "

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/docs.ja-jp#645]
https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/images-bitmaps-and-metafiles

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0a8e2b2f-cbaf-9ca5-9343-b1b45da1f6ab
* Version Independent ID: 7502ae3b-14e9-f95e-ba3a-481c4b6b453e
* Content: [イメージ、ビットマップ、およびメタファイル](https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/images-bitmaps-and-metafiles)
* Content Source: [docs/framework/winforms/advanced/images-bitmaps-and-metafiles.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/framework/winforms/advanced/images-bitmaps-and-metafiles.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/images-bitmaps-and-metafiles

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
