### ISSUE TITLE
[LOC] English is displayed in the title. "Windows Forms and Unmanaged Applications Overview" 

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/docs.ja-jp#648]
https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/windows-forms-and-unmanaged-applications-overview

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4713b5b1-4455-b625-87a6-484c5d7df915
* Version Independent ID: 74aef019-42ad-6593-1fd0-0c77b14224a2
* Content: [Windows フォームおよびアンマネージ アプリケーションの概要](https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/windows-forms-and-unmanaged-applications-overview)
* Content Source: [docs/framework/winforms/advanced/windows-forms-and-unmanaged-applications-overview.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/framework/winforms/advanced/windows-forms-and-unmanaged-applications-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by hyoshioka0128** [comment]
Close #648

**Comment by hyoshioka0128** [comment]
Close #648

**Comment by hyoshioka0128** [comment]
Close  #648
related issues: #649 | #650
