### ISSUE TITLE
[LOC]English is displayed in the title "Enhancing Windows Forms Applications"

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/docs.ja-jp#649]
https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3e236036-824a-1ec3-3a1e-330260093c54
* Version Independent ID: fdcaed41-5050-0834-f3cf-460e91bcdb24
* Content: [Windows フォーム アプリケーションの拡張](https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/)
* Content Source: [docs/framework/winforms/advanced/index.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/framework/winforms/advanced/index.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
