### ISSUE TITLE
[LOC]English is displayed in the title "Graphics and Drawing in Windows Forms"

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/docs.ja-jp#650]
https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/graphics-and-drawing-in-windows-forms

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b1a21a43-c039-3b56-bb72-479e88fcab69
* Version Independent ID: aeb702bd-8f2f-7729-41f6-90c2bde25b30
* Content: [Windows フォームにおけるグラフィックスと描画](https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/graphics-and-drawing-in-windows-forms)
* Content Source: [docs/framework/winforms/advanced/graphics-and-drawing-in-windows-forms.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/framework/winforms/advanced/graphics-and-drawing-in-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/graphics-and-drawing-in-windows-forms 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
