### ISSUE TITLE
Wrong Japanese translation

### ISSUE THREAD

**Issue by vorfee** [dotnet/docs.ja-jp#69]
```csharp
[Export] //WILL NOT match the previous import!  
public class MyLogger : IMyAddin { }
```

This contract type is `MyLogger`. But Japanese translation means "This contract type is `IMyAddin`".

Incorrect: "このエクスポートのコントラクト型は、 MyLogger ではなく IMyAddin です。"
Correct: "このエクスポートのコントラクト型は、 IMyAddin ではなく MyLogger です。"

**Comment by nokura** [comment]
Thank you for your input. I am looking into it. 
If you could create PR with your suggested translation, I would highly appreciate it.

**Comment by nokura** [comment]
Hello @vorfee 
Thank you for your input. Will you confirm if this is the target topic that you add your suggestion for?
https://docs.microsoft.com/ja-jp/dotnet/framework/mef/attributed-programming-model-overview-mef

**Comment by CeciAc** [comment]
Closed after no further replies nor PR created.
If linguistic issue persist, please create a PR so we can work on it.
