### ISSUE TITLE
"For Each...Next" statements are mistranslated as "ごとにしています...次へ"

### ISSUE THREAD

**Issue by nogic1008** [dotnet/docs.ja-jp#709]
Related: dotnet/dotnet-api-docs.ja-jp#98

`For Each ... Next` is a VB.NET statement that should not be translated, but it is machine translated.

I found it in the following file:
- [反復子 (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/modifiers/iterator.md)
- [For...Next ステートメント (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/statements/for-next-statement.md)
- [Function ステートメント (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/statements/function-statement.md)
- [Option Strict ステートメント (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/statements/option-strict-statement.md)
- [Yield ステートメント (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/statements/yield-statement.md)
- [コレクション (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/concepts/collections.md)
- [反復子 (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/concepts/iterators.md)
- [Visual Basic におけるステートメント](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/language-features/statements.md)
- [Visual Basic における配列](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/language-features/arrays/index.md)
- [ループ構造 (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/language-features/control-flow/loop-structures.md)
- [拡大変換と縮小変換 (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/language-features/data-types/widening-and-narrowing-conversions.md)
- [Visual Basic のオブジェクトとクラス](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/language-features/objects-and-classes/index.md)

Since I searched from the [docs web site](https://docs.microsoft.com/ja-jp/search/index?search=%22%E3%81%94%E3%81%A8%E3%81%AB%E3%81%97%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%22&scope=.NET), there may be other documents with this problem.

**Comment by nogic1008** [comment]
I also found that VB.NET statements mistranslated like below, but they need to be treated as new issues.
- `Try...Catch..Finally` -> お試しください.キャッチしてください.最後に
- `For...Next` -> をしています.次へ
-  `Select...Case` -> を選択しています.Case
-  `While...End While` -> 中.While 終了
- `Do...Loop` -> の操作を行います.Loop

**Comment by CeciAc** [comment]
Hello, @nogic1008
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Working also with related issue https://github.com/dotnet/dotnet-api-docs.ja-jp/issues/98

> For Each ... Next is a VB.NET statement that should not be translated, but it is machine translated.
> 
> I found it in the following file:
> 
>     [System.Span<T>.Enumerator](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System/Span%601%2BEnumerator.xml)
>     [System.ReadOnlySpan<T>.Enumerator](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System/ReadOnlySpan%601%2BEnumerator.xml)
>     [Microsoft.VisualBasic.Collection](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/Microsoft.VisualBasic/Collection.xml)
>

**Comment by lichasu** [comment]
Hello, @, 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
