### ISSUE TITLE
"Try...Catch..Finally" VB.NET statements are mistranslated as "お試しください.キャッチしてください.最後に"

### ISSUE THREAD

**Issue by nogic1008** [dotnet/docs.ja-jp#713]
Related: #709

I found them in [Docs Search](https://docs.microsoft.com/ja-jp/search/index?search=%22%E3%81%8A%E8%A9%A6%E3%81%97%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84%22&scope=.NET), so there may be other documents with this problem.

### docs.ja-jp Area
- [例外処理の保護](https://github.com/dotnet/docs.ja-jp/blob/live/docs/framework/misc/securing-exception-handling.md)
- [例外とパフォーマンス](https://github.com/dotnet/docs.ja-jp/blob/live/docs/standard/design-guidelines/exceptions-and-performance.md)
- [Await 演算子 (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/operators/await-operator.md)
- [GoTo ステートメント](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/statements/goto-statement.md)
- [Try...Catch...Finally ステートメント (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/statements/try-catch-finally-statement.md)
- [Yield ステートメント (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/statements/yield-statement.md)
- [変数 '\<variablename >' 値が割り当てられる前に、参照によって渡される](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/misc/bc42030.md)
- [変数 '\<variablename >' (構造体変数) の値が割り当てられる前に、参照によって渡される](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/misc/bc42108.md)
- [反復子 (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/concepts/iterators.md)
- [方法: 文字列 (Visual Basic) 内の検索](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/language-features/strings/how-to-search-within-a-string.md)

### dotnet-api-docs.ja-jp Area
- [System.IAsyncDisposable](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System/IAsyncDisposable.xml)

The following is similar contents written in Japanese.

-------
## VB.NETのステートメントである`Try...Catch..Finally`が「お試しください.キャッチしてください.最後に」と誤訳されている

関連: #709

[Docsの検索](https://docs.microsoft.com/ja-jp/search/index?search=%22%E3%81%8A%E8%A9%A6%E3%81%97%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84%22&scope=.NET)で探したので、他にも同様の問題を抱えた文書があるかもしれません。

### docs.ja-jp 領域
- [例外処理の保護](https://github.com/dotnet/docs.ja-jp/blob/live/docs/framework/misc/securing-exception-handling.md)
- [例外とパフォーマンス](https://github.com/dotnet/docs.ja-jp/blob/live/docs/standard/design-guidelines/exceptions-and-performance.md)
- [Await 演算子 (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/operators/await-operator.md)
- [GoTo ステートメント](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/statements/goto-statement.md)
- [Try...Catch...Finally ステートメント (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/statements/try-catch-finally-statement.md)
- [Yield ステートメント (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/statements/yield-statement.md)
- [変数 '\<variablename >' 値が割り当てられる前に、参照によって渡される](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/misc/bc42030.md)
- [変数 '\<variablename >' (構造体変数) の値が割り当てられる前に、参照によって渡される](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/misc/bc42108.md)
- [反復子 (Visual Basic)](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/concepts/iterators.md)
- [方法: 文字列 (Visual Basic) 内の検索](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/language-features/strings/how-to-search-within-a-string.md)

### dotnet-api-docs.ja-jp 領域
- [System.IAsyncDisposable](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System/IAsyncDisposable.xml)

**Comment by nogic1008** [comment]
Related PR: dotnet/dotnet-api-docs.ja-jp#25 , #420

**Comment by CeciAc** [comment]
Hello, @nogic1008
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Microsoft DOCS International Team
Kind regards,
