### ISSUE TITLE
Broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by akiroom** [dotnet/docs.ja-jp#729]
Hi! Thank you for your nice project. I love this project's challenge!

I found a few links are broken.
In [CONTRIBUTING.md](https://github.com/dotnet/docs.ja-jp/blob/live/CONTRIBUTING.md), these links seem to be "404 not found".

- [テンプレート ファイル](https://github.com/dotnet/docs.ja-jp/blob/live/styleguide/template.md)
- [スタイル ガイド](https://github.com/dotnet/docs.ja-jp/blob/live/styleguide/template.md)
- [テンプレート](https://github.com/dotnet/docs.ja-jp/blob/live/styleguide/template.md)
- [スタイルとトーン](https://github.com/dotnet/docs.ja-jp/blob/live/styleguide/voice-tone.md)

I noticed it when I had created #728.
If you have time, please fix it to correct URL.

**Comment by srvbpigh** [comment]
Hello, @akiroom
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@JasonCard FYI

**Comment by JasonCard** [comment]
Hi @akiroom,

Thank you for reporting this issue.
The broken links are now fixed.

Kind regards,
Microsoft DOCS International Team

**Comment by akiroom** [comment]
Hi @JasonCard! Thank you for your fixing. It seems to be good now👍 Thank you!
