### ISSUE TITLE
非同期実装と同期実装の誤訳

### ISSUE THREAD

**Issue by munyabe** [dotnet/docs.ja-jp#787]
「作業負荷」の章で「メソッドが純粋に計算主体の場合、非同期実装としてのみ公開してください。」とありますが、「同期実装」の誤りではないでしょうか。英語の原文では「If a method is purely compute-bound, it should be exposed only as a synchronous implementation. 」とあります。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a50e3d56-6985-0fd2-40b9-155908fec6db
* Version Independent ID: 50355f4c-5763-6977-4b9f-993708037879
* Content: [タスク ベースの非同期パターンの実装](https://docs.microsoft.com/ja-jp/dotnet/standard/asynchronous-programming-patterns/implementing-the-task-based-asynchronous-pattern#feedback)
* Content Source: [docs/standard/asynchronous-programming-patterns/implementing-the-task-based-asynchronous-pattern.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/standard/asynchronous-programming-patterns/implementing-the-task-based-asynchronous-pattern.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by srvbpigh** [comment]
Hello, @munyabe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@munyabe

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/standard/asynchronous-programming-patterns/implementing-the-task-based-asynchronous-pattern  

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
