### ISSUE TITLE
measureの誤訳について

### ISSUE THREAD

**Issue by okagawa** [dotnet/docs.ja-jp#807]
7行目の「最後の2つのメジャーでは」は「最後の2つの基準では」の誤訳かと思います。2行目で「標準的な基準では」とmeasureを「基準」と訳しているためです

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e74bccb0-6965-36db-f998-8e82188f080e
* Version Independent ID: 99af1ae8-9e4a-d5db-5dd4-c5bad9925818
* Content: [ファーストクラス関数](https://docs.microsoft.com/ja-jp/dotnet/fsharp/introduction-to-functional-programming/first-class-functions#feedback)
* Content Source: [docs/fsharp/introduction-to-functional-programming/first-class-functions.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/fsharp/introduction-to-functional-programming/first-class-functions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by srvbpigh** [comment]
Hello, @okagawa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@okagawa

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/fsharp/introduction-to-functional-programming/first-class-functions#feedback 

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
