### ISSUE TITLE
ドメイン イベント ディスパッチャーに関する記述の誤訳

### ISSUE THREAD

**Issue by taiti777** [dotnet/docs.ja-jp#812]
> ドメイン イベントはドメイン イベント ディスパッチャーにプッシュされるメッセージでしかなく、IoC コンテナーまたは他の何らかの方法に基づくインメモリ メディエーターとして実装できます。

この文章では、
「ドメインイベントは、IoC コンテナーまたは他の何らかの方法に基づくインメモリ メディエーターとして実装できます。」と読めます。

実際は以下のようではないでしょうか。
「ドメイン イベントは、(IoC コンテナーまたは他の何らかの方法に基づくインメモリ メディエーターとして実装された)ドメイン イベント ディスパッチャーにプッシュされるだけのメッセージです。」

**Comment by srvbpigh** [comment]
Hello, @taiti777
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@taiti777 様、
コメントをお寄せいただき、誠にありがとうございます。docs.microsoft.com におけるエクスペリエンスの改善に努めておりますが、お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。
**URLはありません**

敬具
Microsoft DOCS インターナショナル チーム

**Comment by taiti777** [comment]
返信遅れて申し訳ありません。

該当する記述の[URL](https://docs.microsoft.com/ja-jp/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation#domain-events-versus-integration-events)です。

**Comment by CeciAc** [comment]
こんにちは、@taiti777

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@taiti777

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation#domain-events-versus-integration-events


記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
