### ISSUE TITLE
日本語翻訳について

### ISSUE THREAD

**Issue by nitahk** [dotnet/docs.ja-jp#814]
Gannen を "ガント" ではなく 元年 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6585f784-ab83-1a98-acc0-a25351702686
* Version Independent ID: 61afd4f7-9445-ef3e-3061-9b4dc71aae6e
* Content: [カレンダーの使用](https://docs.microsoft.com/ja-jp/dotnet/standard/datetime/working-with-calendars#feedback)
* Content Source: [docs/standard/datetime/working-with-calendars.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/standard/datetime/working-with-calendars.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by srvbpigh** [comment]
Hello, @nitahk
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@nitahk

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/standard/datetime/working-with-calendars#feedback  

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
