### ISSUE TITLE
GitHub上の翻訳が反映されていません

### ISSUE THREAD

**Issue by okagawa** [dotnet/docs.ja-jp#826]
GitHub上の翻訳(https://github.com/dotnet/docs.ja-jp/blob/live/docs/fsharp/get-started/index.md)ではなく機械翻訳の結果がそのまま表示されているようです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1ea0ea44-1b46-78cc-77b7-b5345a8b05ca
* Version Independent ID: ad1f303b-793c-6357-4ec0-1822468ca370
* Content: [を概要します。F#](https://docs.microsoft.com/ja-jp/dotnet/fsharp/get-started/#feedback)
* Content Source: [docs/fsharp/get-started/index.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/fsharp/get-started/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by srvbpigh** [comment]
Hello, @okagawa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@okagawa 様、
コメントをお寄せいただき、誠にありがとうございます。docs.microsoft.com におけるエクスペリエンスの改善に努めておりますが、お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。
敬具
Microsoft DOCS インターナショナル チーム

**Comment by CeciAc** [comment]
@okagawa 様、
先にお送りしたコメントについてさらにお知らせいたします。お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。
敬具
Microsoft DOCS インターナショナル チーム

**Comment by CeciAc** [comment]
@okagawa  様、
再度コメントをいただき、ありがとうございます。
大変申し訳ございませんが、いただいたフィードバックを処理するには、依然として情報が不足しております。この度いただいた GitHub の問題はここで終了とさせていただきますが、今後とも、さらにフィードバックをお寄せいただきますよう、お願い申し上げます。
敬具
Microsoft DOCS インターナショナル チーム
