### ISSUE TITLE
Googleやbingの翻訳サービスの方が読みやすい

### ISSUE THREAD

**Issue by okagawa** [dotnet/docs.ja-jp#827]
機械翻訳だと思いますが、用語が一般的な関数型プログラミングで用いられているものと異なり非常に読みづらいです。bing翻訳の方が読みやすいのですが、これに置き換えることはできないでしょうか？
https://www.translatetheweb.com/?ref=TVert&from=&to=ja&a=https://docs.microsoft.com/en-us/dotnet/fsharp/introduction-to-functional-programming/

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1df55ba4-e543-c31c-ba44-e2ae6e78fd33
* Version Independent ID: c88d5609-718e-3df6-6ae5-613438fd8295
* Content: [F# の関数型プログラミングの概要](https://docs.microsoft.com/ja-jp/dotnet/fsharp/introduction-to-functional-programming/)
* Content Source: [docs/fsharp/introduction-to-functional-programming/index.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/fsharp/introduction-to-functional-programming/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by srvbpigh** [comment]
Hello, @okagawa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@okagawa
 フィードバックをお送りいただきありがとうございました。問題のページは機械翻訳されており、常に完全に理解可能であるとは限りません。最近、右側に "英語で読む" オプションが追加されました。このオプションを使用すると、言語設定を変更しなくても英語バージョンに切り替えることができます。 
 敬具 
Microsoft DOCS International Team
