### ISSUE TITLE
タイトルが文字化けしている

### ISSUE THREAD

**Issue by okagawa** [dotnet/docs.ja-jp#828]
タイトル「F#の概要」が「F @ no__t の概要-0」と文字化けして表示されています。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 315ccf12-17ab-44ab-9373-06f0f66f1af5
* Version Independent ID: 0e9bacf2-9afc-36f3-f2db-fb9fc6b8a56d
* Content: [F# とは](https://docs.microsoft.com/ja-jp/dotnet/fsharp/what-is-fsharp#feedback)
* Content Source: [docs/fsharp/what-is-fsharp.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/fsharp/what-is-fsharp.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by srvbpigh** [comment]
Hello, @okagawa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@okagawa
フィードバックをお送りいただきありがとうございました。 
 Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/fsharp/what-is-fsharp#feedback
 記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 
 敬具 
Microsoft DOCS International Team
