### ISSUE TITLE
1行目

### ISSUE THREAD

**Issue by okagawa** [dotnet/docs.ja-jp#842]
1行目が「開始できますF#コンピューターまたはオンライン。」となっていますが、「F#はローカルマシン環境か、オンライン環境から学びはじめることができます。」とした方が良いと思います。
https://github.com/dotnet/docs.ja-jp/blob/live/docs/fsharp/get-started/index.md はすでにそのように書かれていますが、https://docs.microsoft.com/ja-jp/dotnet/fsharp/get-started/ はそうなっていません。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1ea0ea44-1b46-78cc-77b7-b5345a8b05ca
* Version Independent ID: ad1f303b-793c-6357-4ec0-1822468ca370
* Content: [を概要します。F#](https://docs.microsoft.com/ja-jp/dotnet/fsharp/get-started/#feedback)
* Content Source: [docs/fsharp/get-started/index.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/fsharp/get-started/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by srvbpigh** [comment]
Hello, @okagawa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@okagawa

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/fsharp/get-started/

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
