### ISSUE TITLE
タイトルの文字化け

### ISSUE THREAD

**Issue by okagawa** [dotnet/docs.ja-jp#843]
タイトルが「F のインストール#」となっていますが、「F#のインストール」が正しいと思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3f55ac18-83fa-b862-78c9-35507f9663d6
* Version Independent ID: e9634b1d-bc74-da42-82ba-86b5bf1e1579
* Content: [F# をインストールする](https://docs.microsoft.com/ja-jp/dotnet/fsharp/get-started/install-fsharp?tabs=macos)
* Content Source: [docs/fsharp/get-started/install-fsharp.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/fsharp/get-started/install-fsharp.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by srvbpigh** [comment]
Hello, @okagawa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@okagawa

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/fsharp/get-started/install-fsharp?tabs=macos

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
