### ISSUE TITLE
Azure Import and Exportの料金表示

### ISSUE THREAD

**Issue by maku0119** [dotnet/docs.ja-jp#860]
Azure import and exportの「価格の詳細」に「取引手数料」とありますが、「トランザクション料金」の誤りではないでしょうか。特別な費用がかかるように見えます。

*標準のストレージ料金と取引手数料が別途課金されます。
https://azure.microsoft.com/ja-jp/pricing/details/storage-import-export/

**Comment by srvbpigh** [comment]
Hello, @maku0119
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #15599](https://github.com/dotnet/docs/issues/15599) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@maku0119
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/dotnet/docs/issues/15599) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team

**Comment by maku0119** [comment]
My request is to correct the translated phrase in Japanese. The original English document has no issue. The phrase transaction fee should mean the fee calculated with the number of storage transaction, but the phrase is translated to 取引手数料 which means "handling charge for dealing" as if it is the fee of security trading.

**Comment by CeciAc** [comment]
Hi @maku0119 
My mistake, thanks for the clarification!

We are going to review this issue with our linguists

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@maku0119 

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました:   https://azure.microsoft.com/ja-jp/pricing/details/storage-import-export/

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
