### ISSUE TITLE
【Mistranslation】Section : "Build the example" 

### ISSUE THREAD

**Issue by workstyletips** [dotnet/docs.ja-jp#862]
In "Build the example (サンプルをビルドする in japanese)" Section 

4. Because AccessTheWebAsync displays the lengths, the method doesn't need to return anything. Remove the return statement, and change the return type of the method to Task instead of Task<TResult>.

In English, change of return type is from Task<TResult> to Task.
But in Current translation, change of return type is from Task to Task<TResult>.

mistranslation:
return ステートメントを削除し、メソッドの戻り値の型を Task ではなく Task&lt;TResult&gt; に変更します。

correct translation:
return ステートメントを削除し、メソッドの戻り値の型を Task&lt;TResult&gt;  ではなく Taskに変更します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f6505730-911e-b836-01a1-0b0084851d95
* Version Independent ID: b107ea00-08c9-75ef-5cb7-7bad31176e03
* Content: [非同期タスクまたはタスクの一覧のキャンセル (C#)](https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks)
* Content Source: [docs/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @workstyletips
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @workstyletips 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
