### ISSUE TITLE
[LOC]Not Translated

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/docs.ja-jp#912]
"https://docs.microsoft.com/ja-jp/dotnet/visual-basic/programming-guide/language-features/arrays/"
![arrays](https://user-images.githubusercontent.com/40815708/70037043-3cd73c00-15f9-11ea-8564-8d4579a91f07.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 18eeec0c-2b8e-437a-9da6-0fb3517da8f5
* Version Independent ID: a6a57a0c-50c0-d899-3121-f61fc1482fa7
* Content: [配列 - Visual Basic](https://docs.microsoft.com/ja-jp/dotnet/visual-basic/programming-guide/language-features/arrays/)
* Content Source: [docs/visual-basic/programming-guide/language-features/arrays/index.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/programming-guide/language-features/arrays/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/dotnet/visual-basic/programming-guide/language-features/arrays/

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Thank you for your feedback. 

  

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/dotnet/visual-basic/programming-guide/language-features/arrays/.  

 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

 

Kind regards, 

Microsoft DOCS International Team
