### ISSUE TITLE
[LOC]Not Translated (Visual Basic documentation)

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/docs.ja-jp#947]
ja-jp:"https://docs.microsoft.com/ja-jp/dotnet/visual-basic/"

![visual-basic](https://user-images.githubusercontent.com/40815708/70491973-35a6b580-1b46-11ea-8663-f7702bae9b16.png)

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/dotnet/visual-basic/

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
